department/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'department'

urlpatterns = [
    path('', views.index, name='index'),
    path('teachers/<int:teacher_id>/',
         views.teacher_detail,
         name='teacher_detail'),
    path('teachers/create/',
         views.create_teacher,
         name='create_teacher'),
    path('teachers/<int:teacher_id>/edit/',
         views.edit_teacher,
         name='edit_teacher'),
    path('teachers/<int:teacher_id>/delete/',
         views.delete_teacher,
         name='delete_teacher'),
    path('courses/<slug:course_slug>/',
         views.course_detail,
         name='course_detail'),
    path('auth/registration/', views.registration, name='registration'),
    path('auth/password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name='registration/password_change_form.html'
         ),
         name='password_change'),
    path('auth/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='registration/password_change_done.html'
         ),
         name='password_change_done'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

pages/urls.py
from django.urls import path
from .views import AboutView, RulesView


app_name = 'pages'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('rules/', RulesView.as_view(), name='rules'),
]

university/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('department.urls', namespace='department')),
    path('pages/', include('pages.urls', namespace='pages')),
]

handler403 = 'pages.views.custom_403'
handler404 = 'pages.views.custom_404'
handler500 = 'pages.views.custom_500'

department/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Teacher(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Имя преподавателя'
    )
    image = models.ImageField(
        upload_to='teachers/',
        blank=True,
        null=True,
        verbose_name='Изображение'
    )
    position = models.CharField(
        max_length=256,
        verbose_name='Должность'
    )
    full_time = models.BooleanField(
        default=True,
        verbose_name='Работа на полную ставку',
        help_text=''.join([
            'Уберите галочку, ',
            'если преподаватель работает не на полную ставку'
        ])
    )
    additional_work = models.TextField(
        blank=True,
        null=True,
        verbose_name='Дополнительная работа'
    )
    audience = models.ForeignKey(
        'Audience',
        on_delete=models.CASCADE,
        verbose_name='Аудитория'
    )
    courses = models.ManyToManyField(
        'Course',
        related_name='teachers',
        verbose_name='Курсы'
    )

    class Meta:
        verbose_name = 'преподаватель'
        verbose_name_plural = 'преподаватели'
        ordering = ['name']

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Название курса'
    )
    description = models.TextField(
        blank=True,
        verbose_name='Описание курса'
    )

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'
        ordering = ['name']

    def __str__(self):
        return self.name


class Audience(models.Model):
    number = models.CharField(
        max_length=5,
        verbose_name='Номер преподавательской'
    )  

    class Meta:
        verbose_name = 'преподавательская'
        verbose_name_plural = 'преподавательские'
        ordering = ['number']

    def __str__(self):
        return self.number

pages/models.py
from django.db import models

# Create your models here.

department/forms.py
from django import forms
from .models import Teacher
from django.contrib.auth import get_user_model


User = get_user_model()


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'name',
            'position',
            'image',
            'full_time',
            'additional_work',
            'audience',
            'courses'
        ]
        widgets = {
            'courses': forms.CheckboxSelectMultiple,
        }


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

department/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Teacher, Course
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import TeacherForm, UserEditForm
from django.contrib.auth.models import User


def index(request):
    teachers = Teacher.objects.all()
    paginator = Paginator(teachers, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'department/index.html', context)


def teacher_detail(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    context = {'teacher': teacher}
    return render(request, 'department/detail.html', context)


def course_detail(request, course_slug):
    course = get_object_or_404(Course, id=course_slug)
    teachers = Teacher.objects.filter(courses=course).order_by('name')
    context = {
        'course': course,
        'teachers': teachers
    }
    return render(request, 'department/course.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('department:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request,
                  'registration/registration_form.html',
                  context)


@login_required
def create_teacher(request):
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('department:index')
    else:
        form = TeacherForm()
    context = {
        'form': form
    }
    return render(request, 'department/create.html', context)


@login_required
def edit_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('department:teacher_detail',
                            teacher_id=teacher_id)
    else:
        form = TeacherForm(instance=teacher)
    context = {
        'form': form
    }
    return render(request, 'department/create.html', context)


@login_required
def delete_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    if request.method == 'POST':
        teacher.delete()
        return redirect('department:index')
    context = {
        'teacher': teacher
    }
    return render(request, 'department/create.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    context = {
        'user': request.user,
        'profile': user,
    }
    return render(request, 'department/profile.html', context)


@login_required
def edit_profile(request):
    user = get_object_or_404(User, id=request.user.id)
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('department:profile',
                            username=request.user.username)
    else:
        form = UserEditForm(instance=user)
    context = {
        'form': form,
        'user': user,
    }
    return render(request, 'department/user.html', context)

pages/views.py
from django.shortcuts import render
from django.views import View


class AboutView(View):
    def get(self, request):
        return render(request, 'pages/about.html')


class RulesView(View):
    def get(self, request):
        return render(request, 'pages/rules.html')


def custom_403(request, exception):
    return render(request, 'pages/403csrf.html', status=403)


def custom_404(request, exception):
    return render(request, 'pages/404.html', status=404)


def custom_500(request):
    return render(request, 'pages/500.html', status=500)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

templates/department/course.html
{% extends "base.html" %}
{% block title %}
Курс: {{ course.name }}
{% endblock %}
{% block content %}
<h1 class="text-center mb-4">Курс — {{ course.name }}</h1>
<p class="col-6 offset-3 mb-5 lead text-center">{{ course.description }}</p>
<h2 class="text-center mb-4 mt-5">Преподаватели курса:</h2>
{% if teachers %}
<ul class="list-group col-6 offset-3">
    {% for teacher in teachers %}
    <li class="list-group-item">
        <a href="{% url 'department:teacher_detail' teacher.id %}" class="text-decoration-none">{{ teacher.name }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Нет преподавателей для данного курса.</p>
{% endif %}
{% endblock %}

templates/department/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
{% if '/edit/' in request.path %}
Редактирование преподавателя
{% elif "/delete/" in request.path %}
Удаление преподавателя
{% else %}
Добавление преподавателя
{% endif %}
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      {% if '/edit/' in request.path %}
      Редактирование преподавателя
      {% elif '/delete/' in request.path %}
      Удаление преподавателя
      {% else %}
      Добавление преподавателя
      {% endif %}
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if not '/delete/' in request.path %}
        {% bootstrap_form form %}
        {% else %}
        <h5 class="card-title">{{ teacher.name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">Преподавательская: {{ teacher.audience }}</h6>
        <p class="card-text">Должность: {{ teacher.position }}</p>
        <p class="card-text">Работает на полную ставку: {{ teacher.full_time|yesno:"Да,Нет" }}</p>
        <p class="card-text">Курсы:
          {% if teacher.courses.all %}
          {% for course in teacher.courses.all %}
          <a href="{% url 'department:course_detail' course.id %}" class="text-decoration-none">
            {{ course.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
          {% else %}
          нет
          {% endif %}
        </p>
        <p class="card-text">Дополнительная работа: {{ teacher.additional_work|default:"нет" }}</p>
        {% endif %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/department/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ teacher.name }}
{% endblock %}

{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 50rem;">
        <div class="row no-gutters">
            <div class="col-auto">
                {% if teacher.image %}
                <a href="{{ teacher.image.url }}" target="_blank">
                    <img class="border-3 rounded" height="300" src="{{ teacher.image.url }}" alt="{{ teacher.name }}">
                </a>
                {% else %}
                <img class="border-3 rounded" height="300" src="{% static 'img/default_teacher_image.jpg' %}"
                    alt="Изображение отсутствует">
                {% endif %}
            </div>
            <div class="col">
                <div class="card-body">
                    <h5 class="card-title">{{ teacher.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Преподавательская: {{ teacher.audience }}</h6>
                    <p class="card-text">Должность: {{ teacher.position }}</p>
                    <p class="card-text">Работает на полную ставку: {{ teacher.full_time|yesno:"Да,Нет" }}</p>
                    <p class="card-text">Курсы:
                        {% if teacher.courses.all %}
                        {% for course in teacher.courses.all %}
                        <a href="{% url 'department:course_detail' course.id %}" class="text-decoration-none">
                            {{ course.name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        {% else %}
                        нет
                        {% endif %}
                    </p>
                    <p class="card-text">Дополнительная работа: {{ teacher.additional_work|default:"нет" }}</p>
                    <a href="{% url 'department:index' %}" class="btn btn-primary">Назад к преподавателям</a>
                    {% if user.is_authenticated %}
                    <div class="mb-2">
                        <a class="btn btn-sm text-muted" href="{% url 'department:edit_teacher' teacher.id %}"
                            role="button">
                            Отредактировать преподавателя
                        </a>
                        <a class="btn btn-sm text-muted" href="{% url 'department:delete_teacher' teacher.id %}"
                            role="button">
                            Удалить преподавателя
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/department/index.html
{% extends "base.html" %}
{% block title %}
Кафедра
{% endblock %}
{% block content %}
<h1 class="text-center mb-5">Преподаватели кафедры</h1>
{% for teacher in page_obj %}
<article class="mb-5">
    {% include "includes/teacher_card.html" %}
</article>
{% endfor %}
{% include "includes/paginator.html" %}
{% endblock %}

templates/department/profile.html
{% extends "base.html" %}
{% block title %}
Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
<h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
<small>
  <ul class="list-group list-group-horizontal justify-content-center mb-3">
    <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}
      {% else %}не указано{% endif %}</li>
    <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
    <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
  </ul>
  <ul class="list-group list-group-horizontal justify-content-center">
    {% if user.is_authenticated and request.user == profile %}
    <a class="btn btn-sm text-muted" href="{% url 'department:edit_profile' %}">Редактировать профиль</a>
    <a class="btn btn-sm text-muted" href="{% url 'department:password_change' %}">Изменить пароль</a>
    {% endif %}
  </ul>
</small>
<br>
{% include "includes/paginator.html" %}
{% endblock %}

templates/department/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Университет</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'department:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Университет
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav  nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
            О кафедре
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
            Правила
          </a>
        </li>
        {% if user.is_authenticated %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'department:create_teacher' %}">Добавить преподавателя</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'department:profile' user.username %}">{{ user.username }}</a></button>
          <form action="{% url 'logout' %}" method="post" class="btn-group" role="group"
            aria-label="Basic outlined example">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary text-decoration-none">Выйти</button>
          </form>
        </div>
        {% else %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'login' %}">Войти</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'department:registration' %}">Регистрация</a></button>
        </div>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/teacher_card.html
{% load static %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="row no-gutters">
      <div class="col-auto">
        {% if teacher.image %}
        <a href="{{ teacher.image.url }}" target="_blank">
          <img class="border-3 rounded" height="200" src="{{ teacher.image.url }}" alt="{{ teacher.name }}">
        </a>
        {% else %}
        <img class="border-3 rounded" height="200" src="{% static 'img/default_teacher_image.jpg' %}"
          alt="Изображение отсутствует">
        {% endif %}
      </div>
      <div class="col">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{% url 'department:teacher_detail' teacher.id %}" class="text-decoration-none">
              {{ teacher.name }}
            </a>
          </h5>
          <h6 class="card-subtitle mb-2 text-muted">Преподавательская: {{ teacher.audience }}</h6>
          <p class="card-text">Должность: {{ teacher.position }}</p>
          <p class="card-text">Курсы:
            {% if teacher.courses.all %}
            {% for course in teacher.courses.all %}
            <a href="{% url 'department:course_detail' course.id %}" class="text-decoration-none">
              {{ course.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            {% else %}
            нет
            {% endif %}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'department:index' %}">Вернуться на главную</a>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}
{% block title %}
О кафедре
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      О кафедре
    </div>
    <div class="card-body">
      <p>
        Кафедра прикладной математики была основана в 1990 году. Наша кафедра занимается подготовкой
        высококвалифицированных специалистов в области математики и её приложений.
      </p>
      <p>
        Мы стремимся к тому, чтобы наши студенты получали не только теоретические знания, но и практические навыки,
        необходимые для успешной карьеры.
      </p>
      <p>
        Основные направления работы кафедры:
      <ul>
        <li>Обучение студентов по программам бакалавриата и магистратуры</li>
        <li>Научные исследования в области математики и её приложений</li>
        <li>Сотрудничество с промышленностью и научными учреждениями</li>
      </ul>
      </p>
    </div>
  </div>
</div>
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
Наши правила
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      Правила кафедры
    </div>
    <div class="card-body">
      <p>На кафедре прикладной математики действуют следующие правила:</p>
      <ol>
        <li>Студенты обязаны посещать все занятия и активно участвовать в учебном процессе.</li>
        <li>Все курсовые и дипломные работы должны быть выполнены в соответствии с установленными сроками.</li>
        <li>Запрещается использование мобильных телефонов и других электронных устройств на занятиях.</li>
        <li>Студенты должны соблюдать академическую честность и избегать плагиата в своих работах.</li>
        <li>В случае возникновения конфликтных ситуаций, студенты должны обращаться к преподавателям или куратору
          группы.</li>
      </ol>
    </div>
  </div>
</div>
{% endblock %}